### ISSUE TITLE
fix clippy warnings

### ISSUE THREAD

**Issue by redshiftzero** [penumbra-zone/decaf377#3]
In the CI config (as in the main penumbra repo) being added in #2 we have clippy commented out, at some point we can resolve those clippy warnings and re-enable the CI check in this repo

**Comment by hdevalence** [comment]
Yeah, we should decide whether or not to put clippy in CI -- the lints they use change sometimes, which can lead to a frustrating experience where some code that used to be "clippy-ok" is now rejected, even though it's unrelated to whatever you're actually trying to do.

**Comment by redshiftzero** [comment]
closing as unplanned
