### ISSUE TITLE
Add all missing methods, migrate crates to stable release

### ISSUE THREAD

**Issue by cronokirby** [penumbra-zone/decaf377#93]
Right now, several decaf377 dependents like decaf377-rdsa, -ka, etc. were upgraded to recent code changes, but used git tags because of instability related to adding the necessary methods they needed at the last minute.

We should finalize adding these, and then make all of them use a new release we tag.

**Comment by redshiftzero** [comment]
decaf377 was released with the new methods (from #98 and #91) in 0.9.0: https://github.com/penumbra-zone/decaf377/releases/tag/0.9.0

There is wip bumping to a later version of decaf377 in https://github.com/penumbra-zone/penumbra/pull/3806, but the blocker is that the new backend results in a performance hit

**Comment by redshiftzero** [comment]
This is unblocked now: https://crates.io/crates/decaf377/0.10.0

**Comment by TalDerei** [comment]
crates now use https://crates.io/crates/decaf377/0.10.1
